import { chromium } from 'playwright';
const F='/home/eranti/learning-with-ai/docs/index.html';
const D='/tmp/claude-1000/-home-eranti/795498ca-1049-4fbf-9be0-44c3dc673b6d/scratchpad/';
const b=await chromium.launch();
const ctx=await b.newContext({viewport:{width:390,height:844},colorScheme:'light'});
const p=await ctx.newPage();
await p.goto('file://'+F,{waitUntil:'networkidle'});
await p.waitForTimeout(400);
await p.locator('figure').nth(1).screenshot({path:D+'slope-narrow2.png'});
await p.locator('figure').nth(0).screenshot({path:D+'est-narrow2.png'});
await b.close();
